version: "3.8"

services:
  cinemadatabase:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_DB=cinema
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    image: api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8090
      ConnectionStrings:AuthDb: Server=cinemadatabase;Port=5432;User Id=postgres;Password=S3cret;Database=cinema;
    ports:
      - "8090:8090"
    depends_on:
      - cinemadatabase
      
  
volumes:
  db: